#!/usr/bin/env python3
"""Detailed table of the panorama rule (#093 / #096) against the default, from a results_table.py csv -> markdown.

    python scripts/table_panorama_rule.py <results csv> <runs root> > docs/results_panorama_rule_096.md

Per sequence: the columns x upscale the rule chose (from the run log), every metric as mean +- sd over the seeds for the default
(base092) and the rule (autowh093; NCD 2021: up2093, 1024 x 2), and the change in %.  Then per dataset and over all: wins, median
change, Wilcoxon signed-rank test (sequences paired; exact for n <= 25).
"""
import csv
import re
import sys
from pathlib import Path

import numpy as np
from scipy.stats import wilcoxon

BASE = "default of after_091 (upright SURF + guided matching, shift rule), two starts + range fallback (#092)"
RULE = "default of after_091, panorama from the sensor: own columns + square pixels, auto (#093)"
RULE_NCD21 = "default of after_091, panorama upscale 2 instead of 8 (square pixels, Ouster 128, #093)"
METRICS = [("rpe_r", "RPE 1 m rot [°/m]", 3), ("rpe_t", "RPE 1 m tr [cm/m]", 2), ("rpe1s_r", "RPE 1 s rot [°]", 3),
           ("rpe1s_t", "RPE 1 s tr [cm]", 2), ("rte", "RTE [%]", 2), ("rre", "RRE [°/100 m]", 3), ("ate", "APE / score [m]", 3),
           ("z_rmse", "z RMSE [m]", 3), ("excess", "path vs GT [%]", 2), ("fail", "image failures", 1)]
SENSOR = {"Oxford Spires": "Hesai QT64", "Newer College 2021": "Ouster OS0-128", "Newer College 2020": "Ouster OS1-64",
          "Hilti 2021": "Ouster OS0-64", "NTU VIRAL": "Ouster OS1-16"}


def chosen(runs_root, seq_dir_hint):
    for f in Path(runs_root).glob(f"**/{seq_dir_hint}/autowh093_s0.log"):
        t = f.read_text(errors="ignore")
        w = re.search(r"sensor's own\): (\d+)", t); u = re.search(r"square pixels\): ([\d.]+) \((\d+) rows\)", t)
        if w and u:
            return f"{w.group(1)} × {float(u.group(1)):.2f} ({u.group(2)} rows)"
    return None


def main():
    rows = list(csv.DictReader(open(sys.argv[1])))
    root = sys.argv[2]
    get = lambda s, arm: next((r for r in rows if r["sequence"] == s and r["arm"] == arm), None)
    seqs = []
    for s in dict.fromkeys(r["sequence"] for r in rows):
        a = get(s, BASE); b = get(s, RULE) or get(s, RULE_NCD21)
        if a and b:
            seqs.append((s, a, b))
    hints = {"christ-church-02": "church_02", "christ-church-03": "church_03", "keble-college-03": "keble_03",
             "observatory-quarter-01": "observatory_01", "blenheim-palace-02": "blenheim_02", "bodleian-library-02": "bodleian_02",
             "01_short": "newer_college_01_short", "02_long_experiment": "02_long_experiment", "dynamic_spinning": "dynamic_spinning"}
    f = lambda v, n: "—" if not np.isfinite(v) else f"{v:.{n}f}"
    print("# Panorama from the sensor (#093 / #096) — every sequence, default vs rule\n")
    print("*Generated by `scripts/table_panorama_rule.py` from `kiss_runs/results_official_allarms_093b.csv` (2/10/2026). Default = `base092` "
          "(after_091: upright SURF, guided matching, two starts, range fallback; panorama 1024 × 8). Rule = `autowh093` (columns of the sensor, "
          "square pixels, measured from the first scan; NCD 2021: `up2093`, 1024 × 2). Mean ± sd over 4 seeds per sequence; Δ = (rule − default) / "
          "default. Official protocol of each dataset (evo for Spires / NCD; Hilti and NTU: their own score in the APE row, other rows empty). "
          "Lower is better everywhere (path: |excess|). ⏳ not validated.*\n")
    print("## 1. Per dataset (sequences paired, Wilcoxon signed-rank)\n")
    print("| dataset (sensor) | n | metric | rule better – worse | median Δ | p |")
    print("|---|---|---|---|---|---|")
    groups = {}
    for s, a, b in seqs:
        groups.setdefault(a["dataset"], []).append((s, a, b))
    groups["ALL 27"] = seqs
    for ds, items in groups.items():
        for m, lab, _ in METRICS:
            x = np.array([[float(a[m]), float(b[m])] for s, a, b in items])
            if m == "excess":
                x = np.abs(x)
            x = x[np.isfinite(x).all(1)]
            if len(x) < 2 or (m == "fail"):
                continue
            rel = np.median((x[:, 1] - x[:, 0]) / np.where(x[:, 0] == 0, np.nan, x[:, 0])) * 100
            p = wilcoxon(x[:, 1], x[:, 0]).pvalue if len(x) >= 5 and np.any(x[:, 1] != x[:, 0]) else float("nan")
            name = f"{ds} ({SENSOR.get(ds, 'all')})"
            print(f"| {name} | {len(x)} | {lab} | {(x[:, 1] < x[:, 0]).sum()} – {(x[:, 1] > x[:, 0]).sum()} | {rel:+.1f} % | "
                  f"{'—' if not np.isfinite(p) else f'{p:.3f}'} |")
    print("\n## 2. Per sequence\n")
    for ds, items in groups.items():
        if ds == "ALL 27":
            continue
        print(f"### {ds} — {SENSOR.get(ds, '')}\n")
        print("| sequence | rule chose | metric | default | rule | Δ |")
        print("|---|---|---|---|---|---|")
        for s, a, b in items:
            ch = chosen(root, hints.get(s, s)) or ("1024 × 2 (fixed, `up2093`)" if ds == "Newer College 2021" else "?")
            first = True
            for m, lab, n in METRICS:
                va, vb = float(a[m]), float(b[m])
                if not (np.isfinite(va) or np.isfinite(vb)):
                    continue
                sa, sb = float(a[m + "_sd"]), float(b[m + "_sd"])
                d = (abs(vb) - abs(va)) / abs(va) * 100 if np.isfinite(va) and va != 0 else np.nan
                print(f"| {s if first else ''} | {ch if first else ''} | {lab} | {f(va, n)} ± {f(sa, n)} | {f(vb, n)} ± {f(sb, n)} | "
                      f"{'—' if not np.isfinite(d) else f'{d:+.1f} %'} |")
                first = False
        print()


if __name__ == "__main__":
    main()
